#!/bin/bash

source include/get_app_path.inc
source ../ENV

DEBUGGEE_APPLICATION=$(get_app_path ${ENV_DEBUGGEE_APPLICATION})

DEBUGGEE_LIBS=
if [ -n "${ENV_DEBUGGEE_LIBS_PATH}" ]; then
    DEBUGGEE_LIBS=$(get_app_path ${ENV_DEBUGGEE_LIBS_PATH})
    scp ${DEBUGGEE_LIBS}/* ${ENV_TARGET_SSH_HOST}:${ENV_LIBS_UPLOAD_PATH}
fi

scp ${DEBUGGEE_APPLICATION} ${ENV_TARGET_SSH_HOST}:${ENV_APPLICATION_UPLOAD_PATH}
